services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel
        depends_on:
            - postgres
        ports:
            - "8000:8000"

    postgres:
        image: postgres:15
        container_name: postgres_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: myapp_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        networks:
            - laravel

networks:
    laravel:

volumes:
    postgres_data:
